/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HoyRouteImport } from './routes/hoy'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'

const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HoyRoute = HoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacientesRoute,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracion': typeof ConfiguracionRoute
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracion': typeof ConfiguracionRoute
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/servicios': typeof ServiciosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracion': typeof ConfiguracionRoute
  '/hoy': typeof HoyRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/servicios': typeof ServiciosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracion'
    | '/hoy'
    | '/login'
    | '/pacientes'
    | '/servicios'
    | '/solicitudes'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracion'
    | '/hoy'
    | '/login'
    | '/servicios'
    | '/solicitudes'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/configuracion'
    | '/hoy'
    | '/login'
    | '/pacientes'
    | '/servicios'
    | '/solicitudes'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  HoyRoute: typeof HoyRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  ServiciosRoute: typeof ServiciosRoute
  SolicitudesRoute: typeof SolicitudesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoy': {
      id: '/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof HoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
  }
}

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  HoyRoute: HoyRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRouteWithChildren,
  ServiciosRoute: ServiciosRoute,
  SolicitudesRoute: SolicitudesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
